config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :reports, only: [:index, :show]
  resources :uploads, only: [:index] do
    collection { post :import }
  end
  get 'search' => 'search#index'

  root :to => 'reports#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bottom_adwords_url.rb
class BottomAdwordsUrl < ApplicationRecord
  belongs_to :search_result
end

app/models/non_adwords_url.rb
class NonAdwordsUrl < ApplicationRecord
  belongs_to :search_result
end

app/models/report.rb
class Report < ApplicationRecord
  has_many :search_results, -> { order(keyword: 'asc') }

  scope :ordered, -> { order(created_at: 'desc') }

  def to_s
    "#{self.class.name} #{id} - #{created_at.strftime("%A, %B %d, %Y")}"
  end
end

app/models/right_adwords_url.rb
class RightAdwordsUrl < ApplicationRecord
  # TODO: remove it as google killed right hand side ads: https://searchenginewatch.com/2016/02/23/google-kills-right-hand-side-ads-what-does-this-mean-for-sem/
  belongs_to :search_result
end

app/models/search_result.rb
class SearchResult < ApplicationRecord
  belongs_to :report

  has_many :top_adwords_urls
  has_many :bottom_adwords_urls
  has_many :non_adwords_urls
  has_many :right_adwords_urls #TODO it has been removed by Google

  scope :keyword_gteq, -> (query, n) { where("keyword similar to ?", "(%" + query + "%){" + n.to_s + ",}") }
  scope :with_urls, -> do
    self.left_outer_joins(:top_adwords_urls, :bottom_adwords_urls, :non_adwords_urls)
      .where("top_adwords_urls.search_result_id IS NOT NULL OR bottom_adwords_urls.search_result_id IS NOT NULL OR non_adwords_urls.search_result_id IS NOT NULL")
      .distinct
  end

  def build_urls(hash)
    hash[:top_adwords_urls].each do |url|
      self.top_adwords_urls << TopAdwordsUrl.new(url: url)
    end
    hash[:bottom_adwords_urls].each do |url|
      self.bottom_adwords_urls << BottomAdwordsUrl.new(url: url)
    end
    hash[:non_adwords_urls].each do |url|
      self.non_adwords_urls << NonAdwordsUrl.new(url: url)
    end
    hash[:right_adwords_urls].each do |url|
      self.right_adwords_urls << RightAdwordsUrls.new(url: url)
    end
  end
end

app/models/top_adwords_url.rb
class TopAdwordsUrl < ApplicationRecord
  belongs_to :search_result
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController

  def index
    @reports = Report.ordered.paginate(page: params[:page], per_page: 20)
  end

  def show
    @report = Report
      .includes(search_results: [:top_adwords_urls, :bottom_adwords_urls, :non_adwords_urls, :right_adwords_urls])
      .find(params[:id])

    @search_results = @report.search_results.paginate(page: params[:page], per_page: 5)
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  def index
    url_matches = params[:url_matches]
    url_eq = params[:url_eq]
    keyword_gteq_1 = params[:keyword_gteq_1]
    keyword_gteq_2 = params[:keyword_gteq_2]

    @url_matches_count = url_matches_count if url_matches.present?
    @url_eq_count = url_eq_count if url_eq.present?

    if keyword_gteq_2.present? || keyword_gteq_1.present?
      @keyword_gteq_2_count = keyword_gteq_2.present? ? keyword_gteq_2_scope.with_urls.count : 0
      @keyword_gteq_1_count = keyword_gteq_1.present? ? keyword_gteq_1_scope.with_urls.count : 0
      @keyword_gteq_total_count =  @keyword_gteq_2_count + @keyword_gteq_1_count
    end
  end

  private

    def url_matches_count
      TopAdwordsUrl.where('url like ?', "%#{params[:url_matches]}%").count +
      BottomAdwordsUrl.where('url like ?', "%#{params[:url_matches]}%").count
    end

    def url_eq_count
      NonAdwordsUrl.where('url like ?', "#{params[:url_eq]}").count +
      TopAdwordsUrl.where('url like ?', "%#{params[:url_eq]}%").count +
      BottomAdwordsUrl.where('url like ?', "%#{params[:url_eq]}%").count
    end

    def keyword_gteq_2_scope
      SearchResult.keyword_gteq(params[:keyword_gteq_2], 2)
    end

    def keyword_gteq_1_scope
      SearchResult.keyword_gteq(params[:keyword_gteq_1], 1)
    end
end

app/controllers/uploads_controller.rb
require 'csv'

class UploadsController < ApplicationController

  def index; end

  def import
    keywords = CSV.read(params[:file].path).flatten.compact
    WebScraperWorker.perform_async(keywords)
    flash[:notice] = 'Processing in the background. Please refresh page in a few minutes.'
    redirect_to reports_url
  rescue
    flash[:error] = 'Problem with processing your file.'
    redirect_back fallback_location: root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/reports">Reports</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="/uploads">Upload</a></li>
        <li><a href="/search">Search</a></li>
        <%# <li class="dropdown">%>
          <%# <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>%>
          <%# <ul class="dropdown-menu">%>
            <%# <li><a href="#">Action</a></li>%>
            <%# <li><a href="#">Another action</a></li>%>
            <%# <li><a href="#">Something else here</a></li>%>
            <%# <li role="separator" class="divider"></li>%>
            <%# <li><a href="#">Separated link</a></li>%>
            <%# <li role="separator" class="divider"></li>%>
            <%# <li><a href="#">One more separated link</a></li>%>
          <%# </ul>%>
        <%# </li>%>
      <%# </ul>%>
      <%# <form class="navbar-form navbar-left">%>
        <%# <div class="form-group">%>
          <%# <input type="text" class="form-control" placeholder="Search">%>
        <%# </div>%>
        <%# <button type="submit" class="btn btn-default">Submit</button>%>
      <%# </form>%>
      <%# <ul class="nav navbar-nav navbar-right">%>
        <%# <li><a href="#">Link</a></li>%>
        <%# <li class="dropdown">%>
          <%# <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>%>
          <%# <ul class="dropdown-menu">%>
            <%# <li><a href="#">Action</a></li>%>
            <%# <li><a href="#">Another action</a></li>%>
            <%# <li><a href="#">Something else here</a></li>%>
            <%# <li role="separator" class="divider"></li>%>
            <%# <li><a href="#">Separated link</a></li>%>
          <%# </ul>%>
        <%# </li>%>
      <%# </ul>%>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SEO Reports</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
        <% flash.each do |name, msg| %>
          <%= content_tag(:div, msg, class: "alert alert-info") %>
        <% end %>
        <%= yield %>
    </div>
  </body>
</html>

app/views/reports/index.html.erb
<h1>Listing Reports</h1>

<table class='table table-striped'>
  <tr>
    <th>Id</th>
    <th>Created at</th>
    <th>Actions</th>
  </tr>

<% @reports.each do |report| %>
  <tr>
    <td><%= report.id%></td>
    <td><%= report.created_at%></td>
    <td><%= link_to "Show", report, class: 'btn btn-primary'%></td>
  </tr>
<% end %>
</table>

<br>

<%= will_paginate @reports %>

app/views/reports/show.html.erb
<h2><%= @report.to_s %></h2>

<h2><% @search_results.each do |search_result| %></h2>
  <table class='table table-striped'>
    <tr>
      <th><%= SearchResult.human_attribute_name(:id) %></th>
      <th><%= SearchResult.human_attribute_name(:keyword) %></th>
      <th><%= SearchResult.human_attribute_name(:top_adwords_count) %></th>
      <th><%= SearchResult.human_attribute_name(:bottom_adwords_count) %></th>
      <th><%= SearchResult.human_attribute_name(:total_adwords_count) %></th>
      <th><%= SearchResult.human_attribute_name(:non_adwords_results_count) %></th>
      <th><%= SearchResult.human_attribute_name(:total_links_count) %></th>
      <th><%= SearchResult.human_attribute_name(:total_of_search_results) %></th>
    </tr>

    <tr>
      <td><%= search_result.id %></td>
      <td><%= search_result.keyword %></td>
      <td><%= search_result.top_adwords_count %></td>
      <td><%= search_result.bottom_adwords_count %></td>
      <td><%= search_result.total_adwords_count %></td>
      <td><%= search_result.non_adwords_results_count %></td>
      <td><%= search_result.total_links_count %></td>
      <td><%= search_result.total_of_search_results %></td>
    </tr>
  </table>

  <h3>Top Adwords Urls</h2>

  <% search_result.top_adwords_urls.each do |record| %></li>
    <li><%= record.url %></li>
  <% end %>

  <h3>Bottom Adwords Urls</h2>

  <% search_result.bottom_adwords_urls.each do |record| %></li>
    <li><%= record.url %></li>
  <% end %>

  <h3>Non Adwords Urls</h2>

  <% search_result.non_adwords_urls.each do |record| %></li>
    <li><%= record.url %></li>
  <% end %>

  <h3>Right Adwords Urls</h2>

  <% search_result.right_adwords_urls.each do |record| %></li>
    <li><%= record.url %></li>
  <% end %>

<% end %>

<%= will_paginate @search_results %>

app/views/search/index.html.erb
<h2>Search</h2>

<%= form_tag search_path, { method: :get } do %>
  <div class="form-group">
    <%= label_tag(:url_matches, "How many URLs contain the word in Adwords:") %>
    <%= text_field_tag(:url_matches, nil, { class: "form-control" }) %>
  <div>

  <%- if params[:url_matches].present? %>
    <div class="form-group">
      Found:
      <span class="badge">
        <%= @url_matches_count%>
      </span>
    <div>
  <%- end %>

  <br>

  <div class="form-group">
    <%= label_tag(:url_eq, "How many times a specific URL shows up in SEO:") %>
    <%= text_field_tag(:url_eq, nil, { class: "form-control" }) %>
  <div>

  <%- if params[:url_eq].present? %>
    <div class="form-group">
      Found:
      <span class="badge">
        <%= @url_eq_count %>
      </span>
    <div>
  <%- end %>

  <br>

  <div class="form-group">
    <%= label_tag(:keyword_gteq_2, "How many keywords have URLs in SEO with 2+:") %>
    <%= text_field_tag(:keyword_gteq_2, nil, { class: "form-control" }) %>
  <div>


  <div class="form-group">
    <%= label_tag(:keyword_gteq_1, "or 1+")%>
    <%= text_field_tag(:keyword_gteq_1, nil, { class: "form-control" }) %>
  <div>

  <%- if @keyword_gteq_total_count.present? %>
    <div class="form-group">
      Found:
      <span class="badge">
        <%= @keyword_gteq_total_count %>
      </span>
    <div>
  <%- end %>

  <br>

  <%= submit_tag "Search", class: "btn btn-default" %>

<% end %>

app/views/uploads/index.html.erb
<h2>Import Keywords</h2>

<%= form_tag import_uploads_path, multipart: true do %>
  <div class="form-group">
    <label for="file">Select CSV file</label>
    <%= file_field_tag :file %>
    <p class="help-block">*containing maximum 1000 keywords</p>

    <%= submit_tag "Import", class: "btn btn-default" %>
  </div>
<% end %>